name = "ITDickeStates"
uuid = "c56bcc81-0e2c-4527-bc96-4c5479e00cc0"
authors = ["Ryan Levy <rlevy@flatironinstitute.org>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
Combinatorics = "1.0.2"
ITensorMPS = "0.3.17"
ITensors = "0.9.4"
